name: Git Test

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          ls -la
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_ed25519
          echo "${{secrets.SSH_PUBLIC_KEY}}" > ~/.ssh/id_ed25519.pub
          cat ~/.ssh/id_ed25519.pub
          chmod 400 ~/.ssh/*
          ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
          git remote add jsas git@gitlab.com:jsas-development/test.git
          git config --global user.email "atendimento@jsas.com.br"
          git config --global user.name "Jonatas Sas"
          gh --version
          echo "${{github.event.action}}"
          echo "${{env.GITHUB_EVENT_NAME}}"
          echo "${{env.GITHUB_REF}}"
          echo "${{env.GITHUB_HEAD_REF}}"
