name: Git Test

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          ls -la
          echo sucesso, agora estamos em: $CURRENT_BRANCH
        env:
          CURRENT_BRANCH: ${{ github.base_ref }}
