name: Git Test

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          ls -la
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_ed25519
          echo "${{secrets.SSH_PUBLIC_KEY}}" > ~/.ssh/id_ed25519.pub
          cat ~/.ssh/id_ed25519.pub
          chmod 400 ~/.ssh/*
