name: Git Test

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Test
        run: |
          ls -la
          echo sucesso, agora estamos em: $GITHUB_ENV
        env:
          CURRENT_BRANCH: ${{ steps.get_version.outputs.VERSION }}
