name: Git Test

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          mkdir -p /var/www/test
          cd /var/wwww/test
          touch file.txt
          ls -la
