name: Git Test

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          ls -la
          echo sucesso, agora estamos em: $CURRENT_BRANCH - $ACTOR
        env:
          CURRENT_BRANCH: ${{ steps.vars.outputs.tag }}
          ACTOR: ${{ github.actor }}
