name: Git Test

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          ls -la
          set CURRENT_BRANCH=${GITHUB_REF##*/}
          echo running on branch ${GITHUB_REF##*/}
          echo $CURRENT_BRANCH
